services:
  - type: web
    name: nestjs-api
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
